version: '3'

services:
  fastapi:
    build:
      context: ./api
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    env_file:
      - .env.api

  python-bot:
    build:
      context: ./bot
    networks:
      - mynetwork
    depends_on:
      - fastapi
    env_file:
      - .env.bot

networks:
  mynetwork:
